version: '3.7'
services:
  postgres:
    image: postgres:15.1
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  auth-server:
    depends_on:
      - mongodb_container
    build: /auth-server
    environment:
      - DATABASE_LOCAL=mongodb://mongodb_container
    ports:
      - 4000:4000
  redis-cache:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - cache:/data
  app:
    depends_on:
      - postgres
      - redis-cache
      - auth-server
    build: /client
    ports:
      - 3000:3000
volumes:
  mongodb_data_container:
  cache:
